Update fenrir

diff --git a/fenrir b/fenrir
--- a/fenrir
+++ b/fenrir
@@ -19,17 +19,17 @@ RAGSQLPASS=$(date +%s | sha256sum | base64 | head -c 10 ; echo)
 
 # URLs
 URL_RA="https://rathena.org/board"
-URL_RAGIT="https://github.com/rathena/rathena"
-URL_FLUXGIT="https://github.com/rathena/FluxCP"
+URL_RAGIT="https://github.com/rathena/rathena.git"
+URL_FLUXGIT="https://github.com/rathena/FluxCP.git"
 URL_FULLCLIENT="https://drive.google.com/uc?export=download&confirm=Y8ZZ&id=1WnepJCHKlWaPwVnoD4DaXgO-Io07DSbT"
 SERVER_IPLIST=$(ip addr|awk '/eth0/ && /inet/ {gsub(/\/[0-9][0-9]/,""); print $2}')
 SERVER_IP=$(echo $SERVER_IPLIST | cut -d ' ' -f 1 )
 
 if [ $DEV -eq 1 ]
 then
-	VERSION="${INSTALLER_VERSION} - ${YELLOW}Development Script${NC}"
+    VERSION="${INSTALLER_VERSION} - ${YELLOW}Development Script${NC}"
 else
-	VERSION="${INSTALLER_VERSION}"
+    VERSION="${INSTALLER_VERSION}"
 fi
 
 echo "\033c"
@@ -37,11 +37,9 @@ echo "Welcome to ${BLUE}fenrirmachine${NC}, an unattended installer by gamingmag
 echo "Version: ${VERSION}\n"
 echo "This script will now begin to install stuff on your system. Please be patient as this could take a while!\n"
 
-
-
 echo "${BLUE}Step 1/${STEPS}:${NC} Updating your OS"
-apt-get -qy update > /dev/null
-apt-get -qy upgrade > /dev/null
+yes | apt-get -qy update > /dev/null
+yes | apt-get -qy upgrade > /dev/null
 echo ""
 
 apt-get install xfonts-base
@@ -64,10 +62,32 @@ bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password
 bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password_again password ragnarok"'
 
 apt-get -qy install mariadb-server
-wget -q https://raw.githubusercontent.com/gamingmagic/unattended-installer/master/msi.sh
-chmod +x msi.sh
-./msi.sh
-rm msi.sh
+
+# Run the expect script to automatically configure MySQL
+/usr/bin/expect <<EOF
+spawn /usr/bin/mysql_secure_installation
+
+expect "Enter current password for root (enter for none):"
+send "ragnarok\r"
+
+expect "Change the root password?"
+send "n\r"
+
+expect "Remove anonymous users?"
+send "y\r"
+
+expect "Disallow root login remotely?"
+send "y\r"
+
+expect "Remove test database and access to it?"
+send "y\r"
+
+expect "Reload privilege tables now?"
+send "y\r"
+
+interact
+EOF
+
 
 
 
@@ -96,9 +116,23 @@ echo ""
 
 echo "${BLUE}Step 6/${STEPS}:${NC} Installing rA specific packages"
 echo " * Installing git, make, g++"
-apt-get -qy install git make libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat > /dev/null
+if ! apt-get -qy install git make g++; then
+    echo "Failed to install git, make, g++"
+    exit 1
+fi
+
+echo " * Installing MariaDB development libraries"
+if ! apt-get -qy install libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat libmariadb-dev-compat; then
+    echo "Failed to install MariaDB development libraries"
+    exit 1
+fi
+
 echo " * Installing Utilities"
-apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc g++ > /dev/null
+if ! apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc; then
+    echo "Failed to install utilities"
+    exit 1
+fi
+
 echo ""
 
 
